### ISSUE TITLE
Questions about the Logics to Select GPU Cards

### ISSUE THREAD

**Issue by caohe** [elastic-ai/elastic-gpu-scheduler#14]
Hello, I have some questions about the logic of selecting GPU cards:

- In method `Rate`, the score is defined as below:
https://github.com/elastic-ai/elastic-gpu-scheduler/blob/87e3fa4e1d1ac9a47007cd727a0e6e55ae378816/pkg/scheduler/rater.go#L48-L49

  - In this formula, the score is defined as `range / number of allocated GPUs`. 
  - Is this the best objective function that can exactly reflect the Binpack policy, or is it only an approximation?
  - Will it be better to use `variance` as the score?

- In the stages of `Assume/Score/Allocate`, a map is used to cache the scheduling result, which is defined as `allocated map[string]*GPUOption`. 
And the key of this map is defined as the hash of GPURequest:
https://github.com/elastic-ai/elastic-gpu-scheduler/blob/87e3fa4e1d1ac9a47007cd727a0e6e55ae378816/pkg/scheduler/node.go#L62-L64

  - If two pods' GPU requests are same, will it cause a confilct?
  - Otherwise, can we suppose that they can share the same scheduling result?
  - Will it be better to use pod's UID as the key of this map?

Thanks for any reply!

**Comment by caohe** [comment]
@xiaoxubeii @borgerli @payall4u hello, could u please help with this question? 🙏

**Comment by xiaoxubeii** [comment]
1. Rate method
1.1 Is this the best objective function that can exactly reflect the Binpack policy, or is it only an approximation?
Actually it is an very vague approximation. We assume that the binpack will intend to make resource distribution uneven. To be honest, it is a rough algorithm.
2.2 Will it be better to use variance as the score?
Variance is a good algorithm.

2. GPURequest conflicts
It is fine because it has not been allocated before Bind. So we can allow same GPURequest to grab same option.
